export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAILURE = 'GET_ALL_MOVIES_FAILURE';

export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';
export const GET_MOVIE_BY_ID_FAILURE = 'GET_MOVIE_BY_ID_FAILURE';

export const ADD_MOVIE = 'ADD_MOVIE';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE';

export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE';

export const DELETE_MOVIE = 'DELETE_MOVIE';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE';

export const GET_MOVIES_BY_GENRE = 'GET_MOVIES_BY_GENRE';
export const GET_MOVIES_BY_GENRE_SUCCESS = 'GET_MOVIES_BY_GENRE_SUCCESS';
export const GET_MOVIES_BY_GENRE_FAILURE = 'GET_MOVIES_BY_GENRE_FAILURE';

export const GET_MOVIES_BY_FORMAT = 'GET_MOVIES_BY_FORMAT';
export const GET_MOVIES_BY_FORMAT_SUCCESS = 'GET_MOVIES_BY_FORMAT_SUCCESS';
export const GET_MOVIES_BY_FORMAT_FAILURE = 'GET_MOVIES_BY_FORMAT_FAILURE';

export const GET_MOVIES_BY_LANGUAGE = 'GET_MOVIES_BY_LANGUAGE';
export const GET_MOVIES_BY_LANGUAGE_SUCCESS = 'GET_MOVIES_BY_LANGUAGE_SUCCESS';
export const GET_MOVIES_BY_LANGUAGE_FAILURE = 'GET_MOVIES_BY_LANGUAGE_FAILURE';

export const CLEAR_MOVIE_ERROR = 'CLEAR_MOVIE_ERROR';